name: neuroglancer
channels:
  - menpo
  - glemaitre
  - conda-forge
  - defaults
dependencies:
  - python=3.6
  - numpy
  - matplotlib
  - pandas
  - h5py
  - ipywidgets
  - nbserverproxy
  - jupyter_core=4.3.0
  - ipython=5.1.0
  - nbformat=4.3.0
  - pip:
    - git+https://github.com/funkey/nyroglancer
